title: Life Well Balance
description: "Your wellness blog"
timezone: Europe/Stockholm
lang: en
avatar: /assets/img/banner/life-well-balance.svg
email: alex@lifewellbalance.com


collections:
  tabs:
    output: true
    sort_by: order

theme: jekyll-theme-chirpy

plugins:
  - jekyll-archives
  - jekyll-paginate-v2  
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-email-protect

sidebar:
  nav: true

toc: true
baseurl: ""

pagination:
  enabled: true
  per_page: 10
  # permalink: '/page/:num/'
  sort_reverse: true


defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/

  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category     # was: archive
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
 

webmanifest: /assets/img/favicons/manifest.json
favicon:
  sources: []
